apiVersion: v1
kind: Service
metadata:
  name: svc-directory-watcher
spec:
  type: NodePort
  selector:
    app: svc-directory-watcher
  ports:
    - protocol: TCP
      port: 7655
      targetPort: 7655